import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Head from "next/head";
import { ThemeModeScript } from "flowbite-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import '@rainbow-me/rainbowkit/styles.css';
import { Providers } from './providers';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    {/* <Head>
    </Head> */}
    <html lang="en">
      <head>
      <ThemeModeScript />
      </head>
      <body className={`${inter.className}`} >
        <Providers>
          <Navbar/>
          <main>{children}</main>
          <Footer/>
        </Providers>
      </body>
    </html>
    </>
  );
}
